# Generated by Django 4.1.1 on 2022-09-30 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_alter_post_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 3, 59, 31, 522875, tzinfo=datetime.timezone.utc)),
        ),
    ]
