# Generated by Django 4.1.1 on 2022-09-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0002_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
