# Generated by Django 3.0.9 on 2022-10-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0003_alter_follows_id_alter_personalinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
