# Generated by Django 4.1.1 on 2022-10-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0004_auto_20221007_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
