# Generated by Django 3.0.9 on 2022-10-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0005_alter_follows_id_alter_personalinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FavoriteBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_books', models.CharField(max_length=100)),
                ('favorite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalization.PersonalInfo')),
            ],
        ),
    ]
