# Generated by Django 3.0.9 on 2022-10-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0006_auto_20221027_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritebooks',
            old_name='favorite_user',
            new_name='favorite_info',
        ),
    ]
