# Generated by Django 4.1.1 on 2022-09-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerHub', '0002_alter_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, to='readerHub.profile'),
        ),
    ]
