# Generated by Django 4.1.1 on 2022-09-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerHub', '0003_alter_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
